Shared file wasn't working

diff --git a/hooks/command b/hooks/command
--- a/hooks/command
+++ b/hooks/command
@@ -4,8 +4,6 @@ set -eo pipefail
 
 echo "~~~ :docker: docker-control setup" >&2
 
-. "../utils.sh"
-
 SCRIPT=$BUILDKITE_COMMAND
 IMAGE=$BUILDKITE_PLUGIN_DOCKER_CONTROL_IMAGE
 COMPOSE_FILE=$BUILDKITE_PLUGIN_DOCKER_CONTROL_COMPOSE_FILE
@@ -19,6 +17,28 @@ VERBOSE=""
 if [ "$BUILDKITE_PLUGIN_DOCKER_CONTROL_VERBOSE" == "true" ]; then
   VERBOSE="--verbose"
 fi
+
+# retry <number-of-retries> <command>
+function retry {
+  local retries=$1; shift
+  local attempts=1
+  local status=0
+
+  until "$@"; do
+    status=$?
+    echo "Exited with $status"
+    if (( retries == "0" )); then
+      return $status
+    elif (( attempts == retries )); then
+      echo "Failed $attempts retries"
+      return $status
+    else
+      echo "Retrying $((retries - attempts)) more times..."
+      attempts=$((attempts + 1))
+      sleep $(((attempts - 2) * 2))
+    fi
+  done
+}
 
 echo "Running ${CMD} for ${PACKAGE} in ${IMAGE}"
 
