add artifact upload and download

diff --git a/hooks/command b/hooks/command
--- a/hooks/command
+++ b/hooks/command
@@ -9,6 +9,8 @@ IMAGE=$BUILDKITE_PLUGIN_DOCKER_CONTROL_IMAGE
 COMPOSE_FILE=$BUILDKITE_PLUGIN_DOCKER_CONTROL_COMPOSE_FILE
 SERVICE=$BUILDKITE_PLUGIN_DOCKER_CONTROL_SERVICE
 SHOULD_BUILD=$BUILDKITE_PLUGIN_DOCKER_CONTROL_BUILD
+ARTIFACT_DOWNLOAD=$BUILDKITE_PLUGIN_DOCKER_CONTROL_ARTIFACT_DOWNLOAD
+ARTIFACT_UPLOAD=$BUILDKITE_PLUGIN_DOCKER_CONTROL_ARTIFACT_UPLOAD
 export PACKAGE=$BUILDKITE_PLUGIN_DOCKER_CONTROL_PACKAGE
 
 VERBOSE=""
@@ -42,6 +44,16 @@ CMD
 # copy contents of web-code-source to the working directory
 cp -a web-code-source/* .
 
+# download artifact, if specified
+if [ -n "$ARTIFACT_DOWNLOAD" ]; then
+  set +e
+  buildkite-agent artifact download "${ARTIFACT_DOWNLOAD}" .
+  if [ $? -ne 0 ]; then
+    echo "Artifact ${ARTIFACT_DOWNLOAD} not found. Continuing..."
+  fi
+  set -e
+fi
+
 if [ -n "$SHOULD_BUILD" ]; then
   IMAGE=$IMAGE docker-compose $VERBOSE -f $COMPOSE_FILE build $SERVICE
 fi
@@ -53,4 +65,9 @@ then
 else
   echo "+++ :docker: docker-control run" >&2
   IMAGE=$IMAGE docker-compose $VERBOSE -f $COMPOSE_FILE run --rm $SERVICE bash $SCRIPT
+fi
+
+# upload artifact, if specified
+if [ -n "$ARTIFACT_UPLOAD" ]; then
+  buildkite-agent artifact upload "${ARTIFACT_UPLOAD}"
 fi
