update

diff --git a/hooks/pre-exit b/hooks/pre-exit
--- a/hooks/pre-exit
+++ b/hooks/pre-exit
@@ -2,43 +2,25 @@
 
 set -eo pipefail
 
+# ignore SIGTERM sent by buildkite when job is canceled to
+# ensure our cleanup always runs
+trap '' SIGTERM
+
 COMPOSE_FILE=$BUILDKITE_PLUGIN_DOCKER_CONTROL_COMPOSE_FILE
 IMAGE=$BUILDKITE_PLUGIN_DOCKER_CONTROL_IMAGE
 
-FINISHED_LOGS="false"
-FINISHED_CLEANUP="false"
-FINISHED_DISK="false"
+if [ "$BUILDKITE_PLUGIN_DOCKER_CONTROL_LOGS" == "true" ]; then
+echo "~~~ :docker: docker-control service logs" >&2
+  docker-compose -f $COMPOSE_FILE logs --tail="all" > docker-compose-logs.txt
+  buildkite-agent artifact upload docker-compose-logs.txt
+fi
 
-function main() {
-  if [ "$FINISHED_LOGS" == "false" ]; then
-    if [ "$BUILDKITE_PLUGIN_DOCKER_CONTROL_LOGS" == "true" ]; then
-      echo "uploading docker-control service logs..." >&2
-      docker-compose -f $COMPOSE_FILE logs --tail="all" > docker-compose-logs.txt
-      buildkite-agent artifact upload docker-compose-logs.txt
-    fi
+# Try to spin down services
+echo "~~~ :docker: docker-control cleanup" >&2
+docker-compose -f $COMPOSE_FILE kill || true
+docker-compose -f $COMPOSE_FILE down -v || true
+echo "Removing image ${IMAGE}"
+docker image rm "$IMAGE" || true
 
-    FINISHED_LOGS="true"
-  fi
-
-  if [ "$FINISHED_CLEANUP" == "false" ]; then
-    # Try to spin down services
-    docker-compose -f $COMPOSE_FILE kill || true
-    docker-compose -f $COMPOSE_FILE down -v || true
-    echo "Removing image ${IMAGE}"
-    docker image rm "$IMAGE" || true
-
-    FINISHED_CLEANUP="true"
-  fi
-
-  if [ "$FINISHED_DISK" == "false" ]; then
-    # Log out docker disk usage
-    docker system df
-
-    FINISHED_DISK="true"
-  fi
-}
-
-# if the buildkite job was canceled and SIGTERM was sent,
-# retry running anything that hasn't already
-trap main SIGTERM
-main
+# Log out docker disk usage
+docker system df
